# fly.toml app configuration file generated for bitter-violet-2919 on 2023-09-27T09:48:13-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bitter-violet-2919"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

